services:
  pull-boxscores:
    build:
      context: ./pull-boxscores
      dockerfile: Dockerfile
    environment:
      - GS_TEST=${GS_TEST}
    volumes:
      - type: bind
        source: ${LLM_DATA_PATH}
        target: /llm_data
  generate-summaries:
    build:
      context: ./generate-summaries
      dockerfile: Dockerfile
    environment:
      - GS_TEST=${GS_TEST}
    secrets:
      - ANTHROPIC_API_KEY
    volumes:
      - type: bind
        source: ${LLM_DATA_PATH}
        target: /llm_data
    depends_on:
      pull-boxscores:
        condition: service_completed_successfully
secrets:
  ANTHROPIC_API_KEY:
    file: .ANTHROPIC_API_KEY
